Markdown support

diff --git a/engine/build b/engine/build
--- a/engine/build
+++ b/engine/build
@@ -10,14 +10,19 @@ SRC_PATH="$SITE_PATH/src"
 PAGES_PATH="$SRC_PATH/pages"
 ARTICLES_PATH="$SRC_PATH/articles"
 
-# The various pages
+# Check environment
+PANDOC="$(which pandoc || echo -n)"
+
+# Generate the various pages
 
 RESERVED_NAMES="src|engine|README"
 HEADER_FILE="$ENGINE_PATH/header.html"
 FOOTER_FILE="$ENGINE_PATH/footer.html"
 
-for page_file in "$PAGES_PATH"/*; do
-	file="$(basename "$page_file")"
+echo "# Building files"
+
+for input_file in "$PAGES_PATH"/*; do
+	file="$(basename "$input_file")"
 	name="$(echo "$file" | cut -d"." -f1)"
 	extension="$(echo "$file" | cut -d"." -f2)"
 	
@@ -25,8 +30,29 @@ for page_file in "$PAGES_PATH"/*; do
 		continue
 	fi
 	
-	output_file="$SITE_PATH/$name.html"
-	cat "$HEADER_FILE" "$page_file" "$FOOTER_FILE" > $output_file
+	site_file="$name.html"
+	output_file="$SITE_PATH/$site_file"
+	echo "## Generating $site_file"
+	
+	case "$extension" in
+		"html")
+			cat "$HEADER_FILE" "$input_file" "$FOOTER_FILE" > $output_file
+			;;
+			
+		"md")
+			if [ -z "$PANDOC" ]; then
+				echo "ERROR: Pandoc must be installed to use markdown"
+			else
+				cat "$input_file" \
+					| "$PANDOC" -f markdown -t html \
+					| cat "$HEADER_FILE" - "$FOOTER_FILE" > $output_file
+			fi
+			;;
+			
+		*)
+			echo "WARNING: Unknown file type $extension"
+			;;
+	esac
 done
 
 # TODO: The articles
